### ISSUE TITLE
Superscalar.cpp--possibility of changing portBusy matrix prematurely?

### ISSUE THREAD

**Issue by Crotchfire** [SChernykh/RandomX#1]
It appears to be possible in superscalar.cpp, if one were to be in the process of generating a multi-uop instruction (such as imul_rcp), that one could update the portBusy matrix after the first uop, then be forced to discard the instruction altogether due to a failure on the second uop.  This is inconsistent with updates to portBusy when dealing with single uop instructions, so not sure if this is intentional or not.  Perhaps unimportant.

relevant function is line 653, generateSuperscalar
portBusy updates on line 762 in the scheduleMop function

**Comment by SChernykh** [comment]
@tevador ^

**Comment by SChernykh** [comment]
@tevador ~~I think you should move the check `if (cycle1 >= 0)` before the second `scheduleUop`~~ You need to check if `cycle2` is < 0 and restore portBusy in this case.

**Comment by SChernykh** [comment]
@Crotchfire I've checked it and this case doesn't happen for 1,000,000 random superscalar programs, but it still needs fixing in the code to be sure.

**Comment by SChernykh** [comment]
@Crotchfire This is actually not an issue because portBusy is only updated after both cycle1 and cycle2 were found. First 2 calls to scheduleUop are done with `commit == false`.

**Comment by tevador** [comment]
If scheduling on line 762 fails, then the program is completed (`portsSaturated == true` is a terminating condition) and it doesn't matter that `portBusy` is inconsistent with the final program (it's a local variable that's deallocated when `generateSuperscalar` returns).

I don't see a problem here.

**Comment by SChernykh** [comment]
@tevador He was talking about this loop: https://github.com/tevador/RandomX/blob/master/src/superscalar.cpp#L635

It could fail to allocate the second uOp on some cycle, continue and succeed on the next cycle. But since scheduleUop is called with commit == false there, it's not an issue because portBusy is not updated until both scheduleUop succeed.
